id: IB6CCA3EC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:24:37+00:00'
last_modified: '2022-06-07T22:32:03.171901+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12138
  title: ཐར་འོད་སྦྱོང་གསུམ། ༼དཔལ་སྤུངས་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D499:
      image_group_id: I1KG12140
      title: ''
      total_pages: 446
      order: 1
      base_file: D499.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
